name: Run Ansible
on:
  push:
  workflow_dispatch:

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Upgrade pip and install Ansible
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible
      - name: Add the private SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Ansible inventory file for remote host
        run: |
          mkdir -p ./devops/ansible
          export INVENTORY_FILE=./devops/ansible/inventory.ini
          echo "[my_host_group]" > $INVENTORY_FILE
          echo "${{ secrets.AKAMAI_INSTANCE_IP_ADDRESS }}" >> $INVENTORY_FILE
          cat $INVENTORY_FILE
      - name: Ansible default configuration file
        run: |
          mkdir -p ./devops/ansible
          cat <<EOF > ./devops/ansible/ansible.cfg
          [defaults]
          ansible_python_interpreter = '/usr/bin/python3'
          ansible_ssh_private_key_file = ~/.ssh/id_ed25519
          remote_user = root
          inventory = ./inventory.ini
          host_key_checking = False
          EOF
      - name: Ping Ansible hosts
        working-directory: ./devops/ansible
        run: |
          ansible all -m ping
      - name: Deploy nginx via Ansible playbook
        working-directory: ./devops/ansible
        run: |
          ansible-playbook install-nginx.yaml
      - name: Deploy Python via Ansible playbook
        working-directory: ./devops/ansible
        run: |
          ansible-playbook deploy-python.yaml
